//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyWalut.ServiceReferenceKurs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceKurs.ICurrencyService")]
    public interface ICurrencyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetRate", ReplyAction="http://tempuri.org/ICurrencyService/GetRateResponse")]
        string[] GetRate(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetRate", ReplyAction="http://tempuri.org/ICurrencyService/GetRateResponse")]
        System.Threading.Tasks.Task<string[]> GetRateAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetCodes", ReplyAction="http://tempuri.org/ICurrencyService/GetCodesResponse")]
        string[] GetCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetCodes", ReplyAction="http://tempuri.org/ICurrencyService/GetCodesResponse")]
        System.Threading.Tasks.Task<string[]> GetCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetDate", ReplyAction="http://tempuri.org/ICurrencyService/GetDateResponse")]
        string GetDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetDate", ReplyAction="http://tempuri.org/ICurrencyService/GetDateResponse")]
        System.Threading.Tasks.Task<string> GetDateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyServiceChannel : KursyWalut.ServiceReferenceKurs.ICurrencyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyServiceClient : System.ServiceModel.ClientBase<KursyWalut.ServiceReferenceKurs.ICurrencyService>, KursyWalut.ServiceReferenceKurs.ICurrencyService {
        
        public CurrencyServiceClient() {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetRate(string value) {
            return base.Channel.GetRate(value);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRateAsync(string value) {
            return base.Channel.GetRateAsync(value);
        }
        
        public string[] GetCodes() {
            return base.Channel.GetCodes();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCodesAsync() {
            return base.Channel.GetCodesAsync();
        }
        
        public string GetDate() {
            return base.Channel.GetDate();
        }
        
        public System.Threading.Tasks.Task<string> GetDateAsync() {
            return base.Channel.GetDateAsync();
        }
    }
}
